package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlayerinfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerinfoAllPropertiesEquals(Playerinfo expected, Playerinfo actual) {
        assertPlayerinfoAutoGeneratedPropertiesEquals(expected, actual);
        assertPlayerinfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerinfoAllUpdatablePropertiesEquals(Playerinfo expected, Playerinfo actual) {
        assertPlayerinfoUpdatableFieldsEquals(expected, actual);
        assertPlayerinfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerinfoAutoGeneratedPropertiesEquals(Playerinfo expected, Playerinfo actual) {
        assertThat(expected)
            .as("Verify Playerinfo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerinfoUpdatableFieldsEquals(Playerinfo expected, Playerinfo actual) {
        assertThat(expected)
            .as("Verify Playerinfo relevant properties")
            .satisfies(e -> assertThat(e.getPlayerId()).as("check playerId").isEqualTo(actual.getPlayerId()))
            .satisfies(e -> assertThat(e.getPlayerName()).as("check playerName").isEqualTo(actual.getPlayerName()))
            .satisfies(e -> assertThat(e.getBalance()).as("check balance").isEqualTo(actual.getBalance()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerinfoUpdatableRelationshipsEquals(Playerinfo expected, Playerinfo actual) {
        assertThat(expected)
            .as("Verify Playerinfo relationships")
            .satisfies(e -> assertThat(e.getPlayerActivityLogs()).as("check playerActivityLogs").isEqualTo(actual.getPlayerActivityLogs()));
    }
}
