package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlayerActivityLogsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerActivityLogsAllPropertiesEquals(PlayerActivityLogs expected, PlayerActivityLogs actual) {
        assertPlayerActivityLogsAutoGeneratedPropertiesEquals(expected, actual);
        assertPlayerActivityLogsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerActivityLogsAllUpdatablePropertiesEquals(PlayerActivityLogs expected, PlayerActivityLogs actual) {
        assertPlayerActivityLogsUpdatableFieldsEquals(expected, actual);
        assertPlayerActivityLogsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerActivityLogsAutoGeneratedPropertiesEquals(PlayerActivityLogs expected, PlayerActivityLogs actual) {
        assertThat(expected)
            .as("Verify PlayerActivityLogs auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerActivityLogsUpdatableFieldsEquals(PlayerActivityLogs expected, PlayerActivityLogs actual) {
        assertThat(expected)
            .as("Verify PlayerActivityLogs relevant properties")
            .satisfies(e -> assertThat(e.getPlayerId()).as("check playerId").isEqualTo(actual.getPlayerId()))
            .satisfies(e -> assertThat(e.getAction()).as("check action").isEqualTo(actual.getAction()))
            .satisfies(e -> assertThat(e.getBeforeBalance()).as("check beforeBalance").isEqualTo(actual.getBeforeBalance()))
            .satisfies(e -> assertThat(e.getAfterBalance()).as("check afterBalance").isEqualTo(actual.getAfterBalance()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerActivityLogsUpdatableRelationshipsEquals(PlayerActivityLogs expected, PlayerActivityLogs actual) {
        // empty method
    }
}
